# Generated by Django 5.0.6 on 2024-07-17 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0004_rename_categoryname_tb_products_categoryid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_cart',
            fields=[
                ('cartId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Cart Id')),
                ('cartCompleted', models.BooleanField(default=False, verbose_name='Cart Completed')),
                ('cartUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cart User')),
            ],
        ),
        migrations.CreateModel(
            name='tb_cartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartQuantity', models.IntegerField(default=0)),
                ('cartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.tb_cart', verbose_name='Cart Id')),
                ('cartProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.tb_products', verbose_name='Cart Product')),
                ('cartSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.tb_sizes', verbose_name='Cart Size')),
            ],
        ),
    ]
