# Generated by Django 5.0.6 on 2024-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_cart',
            name='cartTotalValue',
            field=models.FloatField(null=True, verbose_name='Total Cart'),
        ),
    ]
