# Generated by Django 5.0.6 on 2024-07-09 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_categories',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False, verbose_name='Category Id')),
                ('categorieName', models.CharField(max_length=80, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='tb_referencies',
            fields=[
                ('referenceId', models.AutoField(primary_key=True, serialize=False, verbose_name='Reference Id')),
                ('referenceDescription', models.TextField(max_length=80, verbose_name='Reference Description')),
            ],
        ),
        migrations.CreateModel(
            name='tb_sizes',
            fields=[
                ('sizeId', models.AutoField(primary_key=True, serialize=False, verbose_name='Size Id')),
                ('sizeName', models.CharField(max_length=30, verbose_name='Size Name')),
            ],
        ),
        migrations.CreateModel(
            name='tb_products',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False, verbose_name='Product Id')),
                ('productName', models.CharField(max_length=80, verbose_name='Product Name')),
                ('productDescription', models.TextField(max_length=150, verbose_name='Product Description')),
                ('productPrice', models.FloatField(verbose_name='Product Price')),
                ('productStock', models.IntegerField(default=1, verbose_name='Product Stock')),
                ('productImage', models.ImageField(upload_to='media/', verbose_name='Product Image')),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.tb_categories', verbose_name='Category Id')),
                ('referenceId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.tb_referencies', verbose_name='Reference Id')),
                ('sizeId', models.ManyToManyField(to='Products.tb_sizes', verbose_name='Size Id')),
            ],
        ),
    ]
