# Generated by Django 5.0.6 on 2024-07-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_products',
            name='referenceId',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Products.tb_referencies', verbose_name='Reference Id'),
        ),
    ]
