# Generated by Django 5.0.6 on 2024-07-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_tb_products_referenceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_products',
            old_name='categoryName',
            new_name='categoryId',
        ),
    ]
