# Generated by Django 5.0.6 on 2024-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_tb_products_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_products',
            name='productImage',
            field=models.ImageField(upload_to='media/', verbose_name='Product Image'),
        ),
    ]
